/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.vcut.tool.apm;

import com.android.build.gradle.AppExtension;
import com.vcut.tool.apm.largeimage.transform.LargeImageTransform;
import com.vcut.tool.apm.largeimage.transform.OkHttpTransform;
import com.vcut.tool.apm.largeimage.transform.UrlConnectionTransform;
import com.vcut.tool.apm.transform.Loger;
import com.vcut.tool.apm.transform.thread.ThreadHookTransform;
import org.gradle.api.Project;
import org.gradle.api.Plugin;

/**
 * 性能相关插件
 */
public class ApmPluginPlugin implements Plugin<Project> {

    public void apply(Project project) {
        Loger.init(project);
        AppExtension appExtension = (AppExtension)project.getProperties().get("android");
        appExtension.registerTransform(new ThreadHookTransform(project));
        appExtension.registerTransform(new LargeImageTransform(project));
        appExtension.registerTransform(new OkHttpTransform(project));
        appExtension.registerTransform(new UrlConnectionTransform(project));
        // Register a task
        project.getTasks().register("greeting", task -> {
            task.doLast(s -> System.out.println("Hello from plugin 'com.vcut.tool.apm.greeting'"));
        });
    }
}
